spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: USER
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect